services:
  - type: web
    name: product-service
    env: java
    plan: free
    buildCommand: "./mvnw clean install"
    startCommand: "java -jar target/*.jar"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: product-db
          property: connectionString
    autoDeploy: true
    healthCheckPath: "/swagger-ui.html"
    regions:
      - oregon

databases:
  - name: product-db
    plan: free
    region: oregon
    postgresVersion: 13
    initialScript:
      - "CREATE SCHEMA IF NOT EXISTS public;"
